services:
  db:
    image: postgres:latest
    container_name: kitelms-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: kitelms
      POSTGRES_PASSWORD: kitelms
      POSTGRES_DB: kitelms
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
