"""adding oauth settings

Revision ID: 51894f49bdc8
Revises: b1f2e4f2dcd5
Create Date: 2025-08-09 20:10:19.593590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51894f49bdc8'
down_revision: Union[str, Sequence[str], None] = 'b1f2e4f2dcd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appsettings', sa.Column('google_client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('appsettings', sa.Column('google_client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('appsettings', sa.Column('google_redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appsettings', 'google_redirect_uri')
    op.drop_column('appsettings', 'google_client_secret')
    op.drop_column('appsettings', 'google_client_id')
    # ### end Alembic commands ###
